### ISSUE TITLE
Link for the WikipediaNLP dataset

### ISSUE THREAD

**Issue by bedapudi6788** [gkiril/OPIEC#1]
Hi, thanks for the wonderful work and dataset. I am unable to find a download link for the "WikipediaNLP" dataset mentioned. The provided link (https://www.uni-mannheim.de/dws/research/resources/opiec/) has only OPIEC data.

Can you please let me know where to find the WikipediaNLP data. Thank you.

**Comment by gkiril** [comment]
The WikipediaNLP dataset will be published soon. Keep checking the page with the data, it should be there by the end of this week.
